# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'loginTest.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_LoginTest(object):
    def setupUi(self, LoginTest):
        LoginTest.setObjectName("LoginTest")
        LoginTest.resize(523, 363)
        self.centralwidget = QtWidgets.QWidget(LoginTest)
        self.centralwidget.setObjectName("centralwidget")
        self.layoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.layoutWidget.setGeometry(QtCore.QRect(50, 40, 371, 181))
        self.layoutWidget.setObjectName("layoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.layoutWidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.findPassword = QtWidgets.QPushButton(self.layoutWidget)
        self.findPassword.setObjectName("findPassword")
        self.gridLayout.addWidget(self.findPassword, 3, 1, 1, 1)
        self.loginIn = QtWidgets.QPushButton(self.layoutWidget)
        self.loginIn.setObjectName("loginIn")
        self.gridLayout.addWidget(self.loginIn, 3, 0, 1, 1)
        self.password = QtWidgets.QLabel(self.layoutWidget)
        self.password.setObjectName("password")
        self.gridLayout.addWidget(self.password, 2, 0, 1, 1)
        self.inputPassword = QtWidgets.QLineEdit(self.layoutWidget)
        self.inputPassword.setObjectName("inputPassword")
        self.gridLayout.addWidget(self.inputPassword, 2, 1, 1, 2)
        self.register_2 = QtWidgets.QPushButton(self.layoutWidget)
        self.register_2.setObjectName("register_2")
        self.gridLayout.addWidget(self.register_2, 3, 2, 1, 1)
        self.login = QtWidgets.QLabel(self.layoutWidget)
        self.login.setObjectName("login")
        self.gridLayout.addWidget(self.login, 0, 0, 1, 1)
        self.inputLogin = QtWidgets.QLineEdit(self.layoutWidget)
        self.inputLogin.setObjectName("inputLogin")
        self.gridLayout.addWidget(self.inputLogin, 0, 1, 1, 2)
        LoginTest.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(LoginTest)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 523, 23))
        self.menubar.setObjectName("menubar")
        LoginTest.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(LoginTest)
        self.statusbar.setObjectName("statusbar")
        LoginTest.setStatusBar(self.statusbar)

        self.retranslateUi(LoginTest)
        QtCore.QMetaObject.connectSlotsByName(LoginTest)

    def retranslateUi(self, LoginTest):
        _translate = QtCore.QCoreApplication.translate
        LoginTest.setWindowTitle(_translate("LoginTest", "MainWindow"))
        self.findPassword.setText(_translate("LoginTest", "找回密码"))
        self.loginIn.setText(_translate("LoginTest", "登录"))
        self.password.setText(_translate("LoginTest", "   密 码："))
        self.register_2.setText(_translate("LoginTest", "注册"))
        self.login.setText(_translate("LoginTest", "   账户名："))
